// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/interfaces.go -destination=internal/mocks/repository_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	models "developer-portal-backend/internal/database/models"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockOrganizationRepositoryInterface is a mock of OrganizationRepositoryInterface interface.
type MockOrganizationRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockOrganizationRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockOrganizationRepositoryInterfaceMockRecorder is the mock recorder for MockOrganizationRepositoryInterface.
type MockOrganizationRepositoryInterfaceMockRecorder struct {
	mock *MockOrganizationRepositoryInterface
}

// NewMockOrganizationRepositoryInterface creates a new mock instance.
func NewMockOrganizationRepositoryInterface(ctrl *gomock.Controller) *MockOrganizationRepositoryInterface {
	mock := &MockOrganizationRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockOrganizationRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrganizationRepositoryInterface) EXPECT() *MockOrganizationRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOrganizationRepositoryInterface) Create(org *models.Organization) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", org)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockOrganizationRepositoryInterfaceMockRecorder) Create(org any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOrganizationRepositoryInterface)(nil).Create), org)
}

// Delete mocks base method.
func (m *MockOrganizationRepositoryInterface) Delete(id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockOrganizationRepositoryInterfaceMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockOrganizationRepositoryInterface)(nil).Delete), id)
}

// GetAll mocks base method.
func (m *MockOrganizationRepositoryInterface) GetAll(limit, offset int) ([]models.Organization, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", limit, offset)
	ret0, _ := ret[0].([]models.Organization)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAll indicates an expected call of GetAll.
func (mr *MockOrganizationRepositoryInterfaceMockRecorder) GetAll(limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockOrganizationRepositoryInterface)(nil).GetAll), limit, offset)
}

// GetByDomain mocks base method.
func (m *MockOrganizationRepositoryInterface) GetByDomain(domain string) (*models.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByDomain", domain)
	ret0, _ := ret[0].(*models.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByDomain indicates an expected call of GetByDomain.
func (mr *MockOrganizationRepositoryInterfaceMockRecorder) GetByDomain(domain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByDomain", reflect.TypeOf((*MockOrganizationRepositoryInterface)(nil).GetByDomain), domain)
}

// GetByID mocks base method.
func (m *MockOrganizationRepositoryInterface) GetByID(id uuid.UUID) (*models.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*models.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockOrganizationRepositoryInterfaceMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockOrganizationRepositoryInterface)(nil).GetByID), id)
}

// GetByName mocks base method.
func (m *MockOrganizationRepositoryInterface) GetByName(name string) (*models.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", name)
	ret0, _ := ret[0].(*models.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockOrganizationRepositoryInterfaceMockRecorder) GetByName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockOrganizationRepositoryInterface)(nil).GetByName), name)
}

// GetWithAllRelations mocks base method.
func (m *MockOrganizationRepositoryInterface) GetWithAllRelations(id uuid.UUID) (*models.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithAllRelations", id)
	ret0, _ := ret[0].(*models.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithAllRelations indicates an expected call of GetWithAllRelations.
func (mr *MockOrganizationRepositoryInterfaceMockRecorder) GetWithAllRelations(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithAllRelations", reflect.TypeOf((*MockOrganizationRepositoryInterface)(nil).GetWithAllRelations), id)
}

// GetWithComponents mocks base method.
func (m *MockOrganizationRepositoryInterface) GetWithComponents(id uuid.UUID) (*models.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithComponents", id)
	ret0, _ := ret[0].(*models.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithComponents indicates an expected call of GetWithComponents.
func (mr *MockOrganizationRepositoryInterfaceMockRecorder) GetWithComponents(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithComponents", reflect.TypeOf((*MockOrganizationRepositoryInterface)(nil).GetWithComponents), id)
}

// GetWithGroups mocks base method.
func (m *MockOrganizationRepositoryInterface) GetWithGroups(id uuid.UUID) (*models.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithGroups", id)
	ret0, _ := ret[0].(*models.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithGroups indicates an expected call of GetWithGroups.
func (mr *MockOrganizationRepositoryInterfaceMockRecorder) GetWithGroups(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithGroups", reflect.TypeOf((*MockOrganizationRepositoryInterface)(nil).GetWithGroups), id)
}

// GetWithLandscapes mocks base method.
func (m *MockOrganizationRepositoryInterface) GetWithLandscapes(id uuid.UUID) (*models.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithLandscapes", id)
	ret0, _ := ret[0].(*models.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithLandscapes indicates an expected call of GetWithLandscapes.
func (mr *MockOrganizationRepositoryInterfaceMockRecorder) GetWithLandscapes(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithLandscapes", reflect.TypeOf((*MockOrganizationRepositoryInterface)(nil).GetWithLandscapes), id)
}

// GetWithMembers mocks base method.
func (m *MockOrganizationRepositoryInterface) GetWithMembers(id uuid.UUID) (*models.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithMembers", id)
	ret0, _ := ret[0].(*models.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithMembers indicates an expected call of GetWithMembers.
func (mr *MockOrganizationRepositoryInterfaceMockRecorder) GetWithMembers(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithMembers", reflect.TypeOf((*MockOrganizationRepositoryInterface)(nil).GetWithMembers), id)
}

// GetWithProjects mocks base method.
func (m *MockOrganizationRepositoryInterface) GetWithProjects(id uuid.UUID) (*models.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithProjects", id)
	ret0, _ := ret[0].(*models.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithProjects indicates an expected call of GetWithProjects.
func (mr *MockOrganizationRepositoryInterfaceMockRecorder) GetWithProjects(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithProjects", reflect.TypeOf((*MockOrganizationRepositoryInterface)(nil).GetWithProjects), id)
}

// Update mocks base method.
func (m *MockOrganizationRepositoryInterface) Update(org *models.Organization) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", org)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockOrganizationRepositoryInterfaceMockRecorder) Update(org any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockOrganizationRepositoryInterface)(nil).Update), org)
}

// MockUserRepositoryInterface is a mock of UserRepositoryInterface interface.
type MockUserRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockUserRepositoryInterfaceMockRecorder is the mock recorder for MockUserRepositoryInterface.
type MockUserRepositoryInterfaceMockRecorder struct {
	mock *MockUserRepositoryInterface
}

// NewMockUserRepositoryInterface creates a new mock instance.
func NewMockUserRepositoryInterface(ctrl *gomock.Controller) *MockUserRepositoryInterface {
	mock := &MockUserRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepositoryInterface) EXPECT() *MockUserRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserRepositoryInterface) Create(member *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", member)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserRepositoryInterfaceMockRecorder) Create(member any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRepositoryInterface)(nil).Create), member)
}

// Delete mocks base method.
func (m *MockUserRepositoryInterface) Delete(id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserRepositoryInterfaceMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserRepositoryInterface)(nil).Delete), id)
}

// GetActiveByOrganization mocks base method.
func (m *MockUserRepositoryInterface) GetActiveByOrganization(orgID uuid.UUID, limit, offset int) ([]models.User, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveByOrganization", orgID, limit, offset)
	ret0, _ := ret[0].([]models.User)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetActiveByOrganization indicates an expected call of GetActiveByOrganization.
func (mr *MockUserRepositoryInterfaceMockRecorder) GetActiveByOrganization(orgID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveByOrganization", reflect.TypeOf((*MockUserRepositoryInterface)(nil).GetActiveByOrganization), orgID, limit, offset)
}

// GetAll mocks base method.
func (m *MockUserRepositoryInterface) GetAll(limit, offset int) ([]models.User, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", limit, offset)
	ret0, _ := ret[0].([]models.User)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAll indicates an expected call of GetAll.
func (mr *MockUserRepositoryInterfaceMockRecorder) GetAll(limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockUserRepositoryInterface)(nil).GetAll), limit, offset)
}

// GetByEmail mocks base method.
func (m *MockUserRepositoryInterface) GetByEmail(email string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", email)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockUserRepositoryInterfaceMockRecorder) GetByEmail(email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockUserRepositoryInterface)(nil).GetByEmail), email)
}

// GetByID mocks base method.
func (m *MockUserRepositoryInterface) GetByID(id uuid.UUID) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRepositoryInterfaceMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRepositoryInterface)(nil).GetByID), id)
}

// GetByName mocks base method.
func (m *MockUserRepositoryInterface) GetByName(name string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", name)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockUserRepositoryInterfaceMockRecorder) GetByName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockUserRepositoryInterface)(nil).GetByName), name)
}

// GetByOrganizationID mocks base method.
func (m *MockUserRepositoryInterface) GetByOrganizationID(orgID uuid.UUID, limit, offset int) ([]models.User, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByOrganizationID", orgID, limit, offset)
	ret0, _ := ret[0].([]models.User)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByOrganizationID indicates an expected call of GetByOrganizationID.
func (mr *MockUserRepositoryInterfaceMockRecorder) GetByOrganizationID(orgID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByOrganizationID", reflect.TypeOf((*MockUserRepositoryInterface)(nil).GetByOrganizationID), orgID, limit, offset)
}

// GetByTeamID mocks base method.
func (m *MockUserRepositoryInterface) GetByTeamID(teamID uuid.UUID, limit, offset int) ([]models.User, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTeamID", teamID, limit, offset)
	ret0, _ := ret[0].([]models.User)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByTeamID indicates an expected call of GetByTeamID.
func (mr *MockUserRepositoryInterfaceMockRecorder) GetByTeamID(teamID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTeamID", reflect.TypeOf((*MockUserRepositoryInterface)(nil).GetByTeamID), teamID, limit, offset)
}

// GetByUserID mocks base method.
func (m *MockUserRepositoryInterface) GetByUserID(userID string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", userID)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockUserRepositoryInterfaceMockRecorder) GetByUserID(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockUserRepositoryInterface)(nil).GetByUserID), userID)
}

// GetExistingUserIDs mocks base method.
func (m *MockUserRepositoryInterface) GetExistingUserIDs(ids []string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExistingUserIDs", ids)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExistingUserIDs indicates an expected call of GetExistingUserIDs.
func (mr *MockUserRepositoryInterfaceMockRecorder) GetExistingUserIDs(ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExistingUserIDs", reflect.TypeOf((*MockUserRepositoryInterface)(nil).GetExistingUserIDs), ids)
}

// GetUserIDsByPrefix mocks base method.
func (m *MockUserRepositoryInterface) GetUserIDsByPrefix(prefix string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserIDsByPrefix", prefix)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserIDsByPrefix indicates an expected call of GetUserIDsByPrefix.
func (mr *MockUserRepositoryInterfaceMockRecorder) GetUserIDsByPrefix(prefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserIDsByPrefix", reflect.TypeOf((*MockUserRepositoryInterface)(nil).GetUserIDsByPrefix), prefix)
}

// GetWithOrganization mocks base method.
func (m *MockUserRepositoryInterface) GetWithOrganization(id uuid.UUID) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithOrganization", id)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithOrganization indicates an expected call of GetWithOrganization.
func (mr *MockUserRepositoryInterfaceMockRecorder) GetWithOrganization(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithOrganization", reflect.TypeOf((*MockUserRepositoryInterface)(nil).GetWithOrganization), id)
}

// SearchByNameOrTitleGlobal mocks base method.
func (m *MockUserRepositoryInterface) SearchByNameOrTitleGlobal(query string, limit, offset int) ([]models.User, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchByNameOrTitleGlobal", query, limit, offset)
	ret0, _ := ret[0].([]models.User)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SearchByNameOrTitleGlobal indicates an expected call of SearchByNameOrTitleGlobal.
func (mr *MockUserRepositoryInterfaceMockRecorder) SearchByNameOrTitleGlobal(query, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchByNameOrTitleGlobal", reflect.TypeOf((*MockUserRepositoryInterface)(nil).SearchByNameOrTitleGlobal), query, limit, offset)
}

// SearchByOrganization mocks base method.
func (m *MockUserRepositoryInterface) SearchByOrganization(orgID uuid.UUID, query string, limit, offset int) ([]models.User, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchByOrganization", orgID, query, limit, offset)
	ret0, _ := ret[0].([]models.User)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SearchByOrganization indicates an expected call of SearchByOrganization.
func (mr *MockUserRepositoryInterfaceMockRecorder) SearchByOrganization(orgID, query, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchByOrganization", reflect.TypeOf((*MockUserRepositoryInterface)(nil).SearchByOrganization), orgID, query, limit, offset)
}

// Update mocks base method.
func (m *MockUserRepositoryInterface) Update(member *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", member)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserRepositoryInterfaceMockRecorder) Update(member any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserRepositoryInterface)(nil).Update), member)
}

// MockGroupRepositoryInterface is a mock of GroupRepositoryInterface interface.
type MockGroupRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockGroupRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockGroupRepositoryInterfaceMockRecorder is the mock recorder for MockGroupRepositoryInterface.
type MockGroupRepositoryInterfaceMockRecorder struct {
	mock *MockGroupRepositoryInterface
}

// NewMockGroupRepositoryInterface creates a new mock instance.
func NewMockGroupRepositoryInterface(ctrl *gomock.Controller) *MockGroupRepositoryInterface {
	mock := &MockGroupRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockGroupRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGroupRepositoryInterface) EXPECT() *MockGroupRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockGroupRepositoryInterface) Create(group *models.Group) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", group)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockGroupRepositoryInterfaceMockRecorder) Create(group any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockGroupRepositoryInterface)(nil).Create), group)
}

// Delete mocks base method.
func (m *MockGroupRepositoryInterface) Delete(id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockGroupRepositoryInterfaceMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockGroupRepositoryInterface)(nil).Delete), id)
}

// GetByID mocks base method.
func (m *MockGroupRepositoryInterface) GetByID(id uuid.UUID) (*models.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*models.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockGroupRepositoryInterfaceMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockGroupRepositoryInterface)(nil).GetByID), id)
}

// GetByName mocks base method.
func (m *MockGroupRepositoryInterface) GetByName(orgID uuid.UUID, name string) (*models.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", orgID, name)
	ret0, _ := ret[0].(*models.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockGroupRepositoryInterfaceMockRecorder) GetByName(orgID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockGroupRepositoryInterface)(nil).GetByName), orgID, name)
}

// GetByOrganizationID mocks base method.
func (m *MockGroupRepositoryInterface) GetByOrganizationID(orgID uuid.UUID, limit, offset int) ([]models.Group, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByOrganizationID", orgID, limit, offset)
	ret0, _ := ret[0].([]models.Group)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByOrganizationID indicates an expected call of GetByOrganizationID.
func (mr *MockGroupRepositoryInterfaceMockRecorder) GetByOrganizationID(orgID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByOrganizationID", reflect.TypeOf((*MockGroupRepositoryInterface)(nil).GetByOrganizationID), orgID, limit, offset)
}

// GetWithOrganization mocks base method.
func (m *MockGroupRepositoryInterface) GetWithOrganization(id uuid.UUID) (*models.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithOrganization", id)
	ret0, _ := ret[0].(*models.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithOrganization indicates an expected call of GetWithOrganization.
func (mr *MockGroupRepositoryInterfaceMockRecorder) GetWithOrganization(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithOrganization", reflect.TypeOf((*MockGroupRepositoryInterface)(nil).GetWithOrganization), id)
}

// GetWithTeams mocks base method.
func (m *MockGroupRepositoryInterface) GetWithTeams(id uuid.UUID) (*models.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithTeams", id)
	ret0, _ := ret[0].(*models.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithTeams indicates an expected call of GetWithTeams.
func (mr *MockGroupRepositoryInterfaceMockRecorder) GetWithTeams(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithTeams", reflect.TypeOf((*MockGroupRepositoryInterface)(nil).GetWithTeams), id)
}

// Search mocks base method.
func (m *MockGroupRepositoryInterface) Search(organizationID uuid.UUID, query string, limit, offset int) ([]models.Group, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", organizationID, query, limit, offset)
	ret0, _ := ret[0].([]models.Group)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Search indicates an expected call of Search.
func (mr *MockGroupRepositoryInterfaceMockRecorder) Search(organizationID, query, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockGroupRepositoryInterface)(nil).Search), organizationID, query, limit, offset)
}

// Update mocks base method.
func (m *MockGroupRepositoryInterface) Update(id uuid.UUID, updates map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", id, updates)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockGroupRepositoryInterfaceMockRecorder) Update(id, updates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockGroupRepositoryInterface)(nil).Update), id, updates)
}

// MockTeamRepositoryInterface is a mock of TeamRepositoryInterface interface.
type MockTeamRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTeamRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockTeamRepositoryInterfaceMockRecorder is the mock recorder for MockTeamRepositoryInterface.
type MockTeamRepositoryInterfaceMockRecorder struct {
	mock *MockTeamRepositoryInterface
}

// NewMockTeamRepositoryInterface creates a new mock instance.
func NewMockTeamRepositoryInterface(ctrl *gomock.Controller) *MockTeamRepositoryInterface {
	mock := &MockTeamRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockTeamRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamRepositoryInterface) EXPECT() *MockTeamRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTeamRepositoryInterface) Create(team *models.Team) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", team)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTeamRepositoryInterfaceMockRecorder) Create(team any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTeamRepositoryInterface)(nil).Create), team)
}

// Delete mocks base method.
func (m *MockTeamRepositoryInterface) Delete(id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTeamRepositoryInterfaceMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTeamRepositoryInterface)(nil).Delete), id)
}

// GetAll mocks base method.
func (m *MockTeamRepositoryInterface) GetAll() ([]models.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]models.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockTeamRepositoryInterfaceMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockTeamRepositoryInterface)(nil).GetAll))
}

// GetByGroupID mocks base method.
func (m *MockTeamRepositoryInterface) GetByGroupID(groupID uuid.UUID, limit, offset int) ([]models.Team, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByGroupID", groupID, limit, offset)
	ret0, _ := ret[0].([]models.Team)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByGroupID indicates an expected call of GetByGroupID.
func (mr *MockTeamRepositoryInterfaceMockRecorder) GetByGroupID(groupID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByGroupID", reflect.TypeOf((*MockTeamRepositoryInterface)(nil).GetByGroupID), groupID, limit, offset)
}

// GetByID mocks base method.
func (m *MockTeamRepositoryInterface) GetByID(id uuid.UUID) (*models.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*models.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTeamRepositoryInterfaceMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTeamRepositoryInterface)(nil).GetByID), id)
}

// GetByName mocks base method.
func (m *MockTeamRepositoryInterface) GetByName(groupID uuid.UUID, name string) (*models.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", groupID, name)
	ret0, _ := ret[0].(*models.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockTeamRepositoryInterfaceMockRecorder) GetByName(groupID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockTeamRepositoryInterface)(nil).GetByName), groupID, name)
}

// GetByNameGlobal mocks base method.
func (m *MockTeamRepositoryInterface) GetByNameGlobal(name string) (*models.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByNameGlobal", name)
	ret0, _ := ret[0].(*models.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByNameGlobal indicates an expected call of GetByNameGlobal.
func (mr *MockTeamRepositoryInterfaceMockRecorder) GetByNameGlobal(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByNameGlobal", reflect.TypeOf((*MockTeamRepositoryInterface)(nil).GetByNameGlobal), name)
}

// GetByOrganizationID mocks base method.
func (m *MockTeamRepositoryInterface) GetByOrganizationID(orgID uuid.UUID, limit, offset int) ([]models.Team, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByOrganizationID", orgID, limit, offset)
	ret0, _ := ret[0].([]models.Team)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByOrganizationID indicates an expected call of GetByOrganizationID.
func (mr *MockTeamRepositoryInterfaceMockRecorder) GetByOrganizationID(orgID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByOrganizationID", reflect.TypeOf((*MockTeamRepositoryInterface)(nil).GetByOrganizationID), orgID, limit, offset)
}

// GetWithMembers mocks base method.
func (m *MockTeamRepositoryInterface) GetWithMembers(id uuid.UUID) (*models.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithMembers", id)
	ret0, _ := ret[0].(*models.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithMembers indicates an expected call of GetWithMembers.
func (mr *MockTeamRepositoryInterfaceMockRecorder) GetWithMembers(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithMembers", reflect.TypeOf((*MockTeamRepositoryInterface)(nil).GetWithMembers), id)
}

// Update mocks base method.
func (m *MockTeamRepositoryInterface) Update(team *models.Team) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", team)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTeamRepositoryInterfaceMockRecorder) Update(team any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTeamRepositoryInterface)(nil).Update), team)
}

// MockProjectRepositoryInterface is a mock of ProjectRepositoryInterface interface.
type MockProjectRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockProjectRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockProjectRepositoryInterfaceMockRecorder is the mock recorder for MockProjectRepositoryInterface.
type MockProjectRepositoryInterfaceMockRecorder struct {
	mock *MockProjectRepositoryInterface
}

// NewMockProjectRepositoryInterface creates a new mock instance.
func NewMockProjectRepositoryInterface(ctrl *gomock.Controller) *MockProjectRepositoryInterface {
	mock := &MockProjectRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockProjectRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectRepositoryInterface) EXPECT() *MockProjectRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockProjectRepositoryInterface) Create(project *models.Project) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", project)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockProjectRepositoryInterfaceMockRecorder) Create(project any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProjectRepositoryInterface)(nil).Create), project)
}

// Delete mocks base method.
func (m *MockProjectRepositoryInterface) Delete(id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockProjectRepositoryInterfaceMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockProjectRepositoryInterface)(nil).Delete), id)
}

// GetByID mocks base method.
func (m *MockProjectRepositoryInterface) GetByID(id uuid.UUID) (*models.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*models.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockProjectRepositoryInterfaceMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockProjectRepositoryInterface)(nil).GetByID), id)
}

// GetByName mocks base method.
func (m *MockProjectRepositoryInterface) GetByName(name string) (*models.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", name)
	ret0, _ := ret[0].(*models.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockProjectRepositoryInterfaceMockRecorder) GetByName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockProjectRepositoryInterface)(nil).GetByName), name)
}

// GetByOrganizationID mocks base method.
func (m *MockProjectRepositoryInterface) GetByOrganizationID(orgID uuid.UUID, limit, offset int) ([]models.Project, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByOrganizationID", orgID, limit, offset)
	ret0, _ := ret[0].([]models.Project)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByOrganizationID indicates an expected call of GetByOrganizationID.
func (mr *MockProjectRepositoryInterfaceMockRecorder) GetByOrganizationID(orgID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByOrganizationID", reflect.TypeOf((*MockProjectRepositoryInterface)(nil).GetByOrganizationID), orgID, limit, offset)
}

// GetHealthURL mocks base method.
func (m *MockProjectRepositoryInterface) GetHealthURL(projectID uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHealthURL", projectID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHealthURL indicates an expected call of GetHealthURL.
func (mr *MockProjectRepositoryInterfaceMockRecorder) GetHealthURL(projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHealthURL", reflect.TypeOf((*MockProjectRepositoryInterface)(nil).GetHealthURL), projectID)
}

// Update mocks base method.
func (m *MockProjectRepositoryInterface) Update(project *models.Project) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", project)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockProjectRepositoryInterfaceMockRecorder) Update(project any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockProjectRepositoryInterface)(nil).Update), project)
}

// MockComponentRepositoryInterface is a mock of ComponentRepositoryInterface interface.
type MockComponentRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockComponentRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockComponentRepositoryInterfaceMockRecorder is the mock recorder for MockComponentRepositoryInterface.
type MockComponentRepositoryInterfaceMockRecorder struct {
	mock *MockComponentRepositoryInterface
}

// NewMockComponentRepositoryInterface creates a new mock instance.
func NewMockComponentRepositoryInterface(ctrl *gomock.Controller) *MockComponentRepositoryInterface {
	mock := &MockComponentRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockComponentRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockComponentRepositoryInterface) EXPECT() *MockComponentRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockComponentRepositoryInterface) Create(component *models.Component) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", component)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockComponentRepositoryInterfaceMockRecorder) Create(component any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockComponentRepositoryInterface)(nil).Create), component)
}

// Delete mocks base method.
func (m *MockComponentRepositoryInterface) Delete(id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockComponentRepositoryInterfaceMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockComponentRepositoryInterface)(nil).Delete), id)
}

// GetByID mocks base method.
func (m *MockComponentRepositoryInterface) GetByID(id uuid.UUID) (*models.Component, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*models.Component)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockComponentRepositoryInterfaceMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockComponentRepositoryInterface)(nil).GetByID), id)
}

// GetByName mocks base method.
func (m *MockComponentRepositoryInterface) GetByName(projectID uuid.UUID, name string) (*models.Component, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", projectID, name)
	ret0, _ := ret[0].(*models.Component)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockComponentRepositoryInterfaceMockRecorder) GetByName(projectID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockComponentRepositoryInterface)(nil).GetByName), projectID, name)
}

// GetByOwnerID mocks base method.
func (m *MockComponentRepositoryInterface) GetByOwnerID(ownerID uuid.UUID, limit, offset int) ([]models.Component, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByOwnerID", ownerID, limit, offset)
	ret0, _ := ret[0].([]models.Component)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByOwnerID indicates an expected call of GetByOwnerID.
func (mr *MockComponentRepositoryInterfaceMockRecorder) GetByOwnerID(ownerID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByOwnerID", reflect.TypeOf((*MockComponentRepositoryInterface)(nil).GetByOwnerID), ownerID, limit, offset)
}

// GetByProjectID mocks base method.
func (m *MockComponentRepositoryInterface) GetByProjectID(projectID uuid.UUID, limit, offset int) ([]models.Component, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByProjectID", projectID, limit, offset)
	ret0, _ := ret[0].([]models.Component)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByProjectID indicates an expected call of GetByProjectID.
func (mr *MockComponentRepositoryInterfaceMockRecorder) GetByProjectID(projectID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByProjectID", reflect.TypeOf((*MockComponentRepositoryInterface)(nil).GetByProjectID), projectID, limit, offset)
}

// GetComponentsByTeamID mocks base method.
func (m *MockComponentRepositoryInterface) GetComponentsByTeamID(teamID uuid.UUID, limit, offset int) ([]models.Component, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetComponentsByTeamID", teamID, limit, offset)
	ret0, _ := ret[0].([]models.Component)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetComponentsByTeamID indicates an expected call of GetComponentsByTeamID.
func (mr *MockComponentRepositoryInterfaceMockRecorder) GetComponentsByTeamID(teamID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetComponentsByTeamID", reflect.TypeOf((*MockComponentRepositoryInterface)(nil).GetComponentsByTeamID), teamID, limit, offset)
}

// Update mocks base method.
func (m *MockComponentRepositoryInterface) Update(component *models.Component) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", component)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockComponentRepositoryInterfaceMockRecorder) Update(component any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockComponentRepositoryInterface)(nil).Update), component)
}

// MockLandscapeRepositoryInterface is a mock of LandscapeRepositoryInterface interface.
type MockLandscapeRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockLandscapeRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockLandscapeRepositoryInterfaceMockRecorder is the mock recorder for MockLandscapeRepositoryInterface.
type MockLandscapeRepositoryInterfaceMockRecorder struct {
	mock *MockLandscapeRepositoryInterface
}

// NewMockLandscapeRepositoryInterface creates a new mock instance.
func NewMockLandscapeRepositoryInterface(ctrl *gomock.Controller) *MockLandscapeRepositoryInterface {
	mock := &MockLandscapeRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockLandscapeRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLandscapeRepositoryInterface) EXPECT() *MockLandscapeRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockLandscapeRepositoryInterface) Create(landscape *models.Landscape) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", landscape)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockLandscapeRepositoryInterfaceMockRecorder) Create(landscape any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockLandscapeRepositoryInterface)(nil).Create), landscape)
}

// Delete mocks base method.
func (m *MockLandscapeRepositoryInterface) Delete(id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockLandscapeRepositoryInterfaceMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockLandscapeRepositoryInterface)(nil).Delete), id)
}

// GetActiveLandscapes mocks base method.
func (m *MockLandscapeRepositoryInterface) GetActiveLandscapes(limit, offset int) ([]models.Landscape, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveLandscapes", limit, offset)
	ret0, _ := ret[0].([]models.Landscape)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetActiveLandscapes indicates an expected call of GetActiveLandscapes.
func (mr *MockLandscapeRepositoryInterfaceMockRecorder) GetActiveLandscapes(limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveLandscapes", reflect.TypeOf((*MockLandscapeRepositoryInterface)(nil).GetActiveLandscapes), limit, offset)
}

// GetByID mocks base method.
func (m *MockLandscapeRepositoryInterface) GetByID(id uuid.UUID) (*models.Landscape, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*models.Landscape)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockLandscapeRepositoryInterfaceMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockLandscapeRepositoryInterface)(nil).GetByID), id)
}

// GetByName mocks base method.
func (m *MockLandscapeRepositoryInterface) GetByName(name string) (*models.Landscape, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", name)
	ret0, _ := ret[0].(*models.Landscape)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockLandscapeRepositoryInterfaceMockRecorder) GetByName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockLandscapeRepositoryInterface)(nil).GetByName), name)
}

// GetByOrganizationID mocks base method.
func (m *MockLandscapeRepositoryInterface) GetByOrganizationID(orgID uuid.UUID, limit, offset int) ([]models.Landscape, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByOrganizationID", orgID, limit, offset)
	ret0, _ := ret[0].([]models.Landscape)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByOrganizationID indicates an expected call of GetByOrganizationID.
func (mr *MockLandscapeRepositoryInterfaceMockRecorder) GetByOrganizationID(orgID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByOrganizationID", reflect.TypeOf((*MockLandscapeRepositoryInterface)(nil).GetByOrganizationID), orgID, limit, offset)
}

// GetByStatus mocks base method.
func (m *MockLandscapeRepositoryInterface) GetByStatus(status string, limit, offset int) ([]models.Landscape, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByStatus", status, limit, offset)
	ret0, _ := ret[0].([]models.Landscape)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByStatus indicates an expected call of GetByStatus.
func (mr *MockLandscapeRepositoryInterfaceMockRecorder) GetByStatus(status, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByStatus", reflect.TypeOf((*MockLandscapeRepositoryInterface)(nil).GetByStatus), status, limit, offset)
}

// GetByType mocks base method.
func (m *MockLandscapeRepositoryInterface) GetByType(orgID uuid.UUID, landscapeType string, limit, offset int) ([]models.Landscape, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByType", orgID, landscapeType, limit, offset)
	ret0, _ := ret[0].([]models.Landscape)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByType indicates an expected call of GetByType.
func (mr *MockLandscapeRepositoryInterfaceMockRecorder) GetByType(orgID, landscapeType, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByType", reflect.TypeOf((*MockLandscapeRepositoryInterface)(nil).GetByType), orgID, landscapeType, limit, offset)
}

// GetLandscapesByProjectID mocks base method.
func (m *MockLandscapeRepositoryInterface) GetLandscapesByProjectID(projectID uuid.UUID, limit, offset int) ([]models.Landscape, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLandscapesByProjectID", projectID, limit, offset)
	ret0, _ := ret[0].([]models.Landscape)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetLandscapesByProjectID indicates an expected call of GetLandscapesByProjectID.
func (mr *MockLandscapeRepositoryInterfaceMockRecorder) GetLandscapesByProjectID(projectID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLandscapesByProjectID", reflect.TypeOf((*MockLandscapeRepositoryInterface)(nil).GetLandscapesByProjectID), projectID, limit, offset)
}

// GetLandscapesByTypeAndStatus mocks base method.
func (m *MockLandscapeRepositoryInterface) GetLandscapesByTypeAndStatus(orgID uuid.UUID, landscapeType, status string, limit, offset int) ([]models.Landscape, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLandscapesByTypeAndStatus", orgID, landscapeType, status, limit, offset)
	ret0, _ := ret[0].([]models.Landscape)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetLandscapesByTypeAndStatus indicates an expected call of GetLandscapesByTypeAndStatus.
func (mr *MockLandscapeRepositoryInterfaceMockRecorder) GetLandscapesByTypeAndStatus(orgID, landscapeType, status, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLandscapesByTypeAndStatus", reflect.TypeOf((*MockLandscapeRepositoryInterface)(nil).GetLandscapesByTypeAndStatus), orgID, landscapeType, status, limit, offset)
}

// GetWithFullDetails mocks base method.
func (m *MockLandscapeRepositoryInterface) GetWithFullDetails(id uuid.UUID) (*models.Landscape, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithFullDetails", id)
	ret0, _ := ret[0].(*models.Landscape)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithFullDetails indicates an expected call of GetWithFullDetails.
func (mr *MockLandscapeRepositoryInterfaceMockRecorder) GetWithFullDetails(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithFullDetails", reflect.TypeOf((*MockLandscapeRepositoryInterface)(nil).GetWithFullDetails), id)
}

// GetWithOrganization mocks base method.
func (m *MockLandscapeRepositoryInterface) GetWithOrganization(id uuid.UUID) (*models.Landscape, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithOrganization", id)
	ret0, _ := ret[0].(*models.Landscape)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithOrganization indicates an expected call of GetWithOrganization.
func (mr *MockLandscapeRepositoryInterfaceMockRecorder) GetWithOrganization(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithOrganization", reflect.TypeOf((*MockLandscapeRepositoryInterface)(nil).GetWithOrganization), id)
}

// GetWithProjects mocks base method.
func (m *MockLandscapeRepositoryInterface) GetWithProjects(id uuid.UUID) (*models.Landscape, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithProjects", id)
	ret0, _ := ret[0].(*models.Landscape)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithProjects indicates an expected call of GetWithProjects.
func (mr *MockLandscapeRepositoryInterfaceMockRecorder) GetWithProjects(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithProjects", reflect.TypeOf((*MockLandscapeRepositoryInterface)(nil).GetWithProjects), id)
}

// Search mocks base method.
func (m *MockLandscapeRepositoryInterface) Search(orgID uuid.UUID, query string, limit, offset int) ([]models.Landscape, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", orgID, query, limit, offset)
	ret0, _ := ret[0].([]models.Landscape)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Search indicates an expected call of Search.
func (mr *MockLandscapeRepositoryInterfaceMockRecorder) Search(orgID, query, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockLandscapeRepositoryInterface)(nil).Search), orgID, query, limit, offset)
}

// SetStatus mocks base method.
func (m *MockLandscapeRepositoryInterface) SetStatus(landscapeID uuid.UUID, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetStatus", landscapeID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetStatus indicates an expected call of SetStatus.
func (mr *MockLandscapeRepositoryInterfaceMockRecorder) SetStatus(landscapeID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStatus", reflect.TypeOf((*MockLandscapeRepositoryInterface)(nil).SetStatus), landscapeID, status)
}

// Update mocks base method.
func (m *MockLandscapeRepositoryInterface) Update(landscape *models.Landscape) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", landscape)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockLandscapeRepositoryInterfaceMockRecorder) Update(landscape any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockLandscapeRepositoryInterface)(nil).Update), landscape)
}

// MockCategoryRepositoryInterface is a mock of CategoryRepositoryInterface interface.
type MockCategoryRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCategoryRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockCategoryRepositoryInterfaceMockRecorder is the mock recorder for MockCategoryRepositoryInterface.
type MockCategoryRepositoryInterfaceMockRecorder struct {
	mock *MockCategoryRepositoryInterface
}

// NewMockCategoryRepositoryInterface creates a new mock instance.
func NewMockCategoryRepositoryInterface(ctrl *gomock.Controller) *MockCategoryRepositoryInterface {
	mock := &MockCategoryRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockCategoryRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCategoryRepositoryInterface) EXPECT() *MockCategoryRepositoryInterfaceMockRecorder {
	return m.recorder
}

// GetAll mocks base method.
func (m *MockCategoryRepositoryInterface) GetAll(limit, offset int) ([]models.Category, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", limit, offset)
	ret0, _ := ret[0].([]models.Category)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAll indicates an expected call of GetAll.
func (mr *MockCategoryRepositoryInterfaceMockRecorder) GetAll(limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockCategoryRepositoryInterface)(nil).GetAll), limit, offset)
}

// GetByID mocks base method.
func (m *MockCategoryRepositoryInterface) GetByID(id uuid.UUID) (*models.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*models.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockCategoryRepositoryInterfaceMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockCategoryRepositoryInterface)(nil).GetByID), id)
}

// MockLinkRepositoryInterface is a mock of LinkRepositoryInterface interface.
type MockLinkRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockLinkRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockLinkRepositoryInterfaceMockRecorder is the mock recorder for MockLinkRepositoryInterface.
type MockLinkRepositoryInterfaceMockRecorder struct {
	mock *MockLinkRepositoryInterface
}

// NewMockLinkRepositoryInterface creates a new mock instance.
func NewMockLinkRepositoryInterface(ctrl *gomock.Controller) *MockLinkRepositoryInterface {
	mock := &MockLinkRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockLinkRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinkRepositoryInterface) EXPECT() *MockLinkRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockLinkRepositoryInterface) Create(link *models.Link) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", link)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockLinkRepositoryInterfaceMockRecorder) Create(link any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockLinkRepositoryInterface)(nil).Create), link)
}

// Delete mocks base method.
func (m *MockLinkRepositoryInterface) Delete(id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockLinkRepositoryInterfaceMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockLinkRepositoryInterface)(nil).Delete), id)
}

// GetByID mocks base method.
func (m *MockLinkRepositoryInterface) GetByID(id uuid.UUID) (*models.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*models.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockLinkRepositoryInterfaceMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockLinkRepositoryInterface)(nil).GetByID), id)
}

// GetByIDs mocks base method.
func (m *MockLinkRepositoryInterface) GetByIDs(ids []uuid.UUID) ([]models.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDs", ids)
	ret0, _ := ret[0].([]models.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDs indicates an expected call of GetByIDs.
func (mr *MockLinkRepositoryInterfaceMockRecorder) GetByIDs(ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDs", reflect.TypeOf((*MockLinkRepositoryInterface)(nil).GetByIDs), ids)
}

// GetByOwner mocks base method.
func (m *MockLinkRepositoryInterface) GetByOwner(owner uuid.UUID) ([]models.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByOwner", owner)
	ret0, _ := ret[0].([]models.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByOwner indicates an expected call of GetByOwner.
func (mr *MockLinkRepositoryInterfaceMockRecorder) GetByOwner(owner any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByOwner", reflect.TypeOf((*MockLinkRepositoryInterface)(nil).GetByOwner), owner)
}

// Update mocks base method.
func (m *MockLinkRepositoryInterface) Update(link *models.Link) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", link)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockLinkRepositoryInterfaceMockRecorder) Update(link any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockLinkRepositoryInterface)(nil).Update), link)
}

// MockDocumentationRepositoryInterface is a mock of DocumentationRepositoryInterface interface.
type MockDocumentationRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockDocumentationRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockDocumentationRepositoryInterfaceMockRecorder is the mock recorder for MockDocumentationRepositoryInterface.
type MockDocumentationRepositoryInterfaceMockRecorder struct {
	mock *MockDocumentationRepositoryInterface
}

// NewMockDocumentationRepositoryInterface creates a new mock instance.
func NewMockDocumentationRepositoryInterface(ctrl *gomock.Controller) *MockDocumentationRepositoryInterface {
	mock := &MockDocumentationRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockDocumentationRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDocumentationRepositoryInterface) EXPECT() *MockDocumentationRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDocumentationRepositoryInterface) Create(doc *models.Documentation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", doc)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDocumentationRepositoryInterfaceMockRecorder) Create(doc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDocumentationRepositoryInterface)(nil).Create), doc)
}

// Delete mocks base method.
func (m *MockDocumentationRepositoryInterface) Delete(id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDocumentationRepositoryInterfaceMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDocumentationRepositoryInterface)(nil).Delete), id)
}

// GetAll mocks base method.
func (m *MockDocumentationRepositoryInterface) GetAll(limit, offset int) ([]models.Documentation, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", limit, offset)
	ret0, _ := ret[0].([]models.Documentation)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAll indicates an expected call of GetAll.
func (mr *MockDocumentationRepositoryInterfaceMockRecorder) GetAll(limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockDocumentationRepositoryInterface)(nil).GetAll), limit, offset)
}

// GetByID mocks base method.
func (m *MockDocumentationRepositoryInterface) GetByID(id uuid.UUID) (*models.Documentation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*models.Documentation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockDocumentationRepositoryInterfaceMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockDocumentationRepositoryInterface)(nil).GetByID), id)
}

// GetByTeamID mocks base method.
func (m *MockDocumentationRepositoryInterface) GetByTeamID(teamID uuid.UUID) ([]models.Documentation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTeamID", teamID)
	ret0, _ := ret[0].([]models.Documentation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTeamID indicates an expected call of GetByTeamID.
func (mr *MockDocumentationRepositoryInterfaceMockRecorder) GetByTeamID(teamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTeamID", reflect.TypeOf((*MockDocumentationRepositoryInterface)(nil).GetByTeamID), teamID)
}

// Update mocks base method.
func (m *MockDocumentationRepositoryInterface) Update(doc *models.Documentation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", doc)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDocumentationRepositoryInterfaceMockRecorder) Update(doc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDocumentationRepositoryInterface)(nil).Update), doc)
}

// MockPluginRepositoryInterface is a mock of PluginRepositoryInterface interface.
type MockPluginRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPluginRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockPluginRepositoryInterfaceMockRecorder is the mock recorder for MockPluginRepositoryInterface.
type MockPluginRepositoryInterfaceMockRecorder struct {
	mock *MockPluginRepositoryInterface
}

// NewMockPluginRepositoryInterface creates a new mock instance.
func NewMockPluginRepositoryInterface(ctrl *gomock.Controller) *MockPluginRepositoryInterface {
	mock := &MockPluginRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockPluginRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPluginRepositoryInterface) EXPECT() *MockPluginRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPluginRepositoryInterface) Create(plugin *models.Plugin) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", plugin)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPluginRepositoryInterfaceMockRecorder) Create(plugin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPluginRepositoryInterface)(nil).Create), plugin)
}

// Delete mocks base method.
func (m *MockPluginRepositoryInterface) Delete(id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPluginRepositoryInterfaceMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPluginRepositoryInterface)(nil).Delete), id)
}

// GetAll mocks base method.
func (m *MockPluginRepositoryInterface) GetAll(limit, offset int) ([]models.Plugin, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", limit, offset)
	ret0, _ := ret[0].([]models.Plugin)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAll indicates an expected call of GetAll.
func (mr *MockPluginRepositoryInterfaceMockRecorder) GetAll(limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockPluginRepositoryInterface)(nil).GetAll), limit, offset)
}

// GetByID mocks base method.
func (m *MockPluginRepositoryInterface) GetByID(id uuid.UUID) (*models.Plugin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*models.Plugin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPluginRepositoryInterfaceMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPluginRepositoryInterface)(nil).GetByID), id)
}

// GetByName mocks base method.
func (m *MockPluginRepositoryInterface) GetByName(name string) (*models.Plugin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", name)
	ret0, _ := ret[0].(*models.Plugin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockPluginRepositoryInterfaceMockRecorder) GetByName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockPluginRepositoryInterface)(nil).GetByName), name)
}

// Update mocks base method.
func (m *MockPluginRepositoryInterface) Update(plugin *models.Plugin) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", plugin)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPluginRepositoryInterfaceMockRecorder) Update(plugin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPluginRepositoryInterface)(nil).Update), plugin)
}
